### ISSUE TITLE
KineticSdk.MakeTransfer not working as expect

### ISSUE THREAD

**Issue by wirelessjeano** [kin-labs/kinetic-unity-sdk#16]
I created two accounts with the token addresses returned of #1 HVDLbCgGbJ98f9MFg2F5bomEGs9QaNUu3DhQ63hWWHuQ and #2 BgnTvag49W5dxiB4utq6PqnkYi9r3HJAPs36Sf5afmiX. 

I then requested an airdrop to token address #1 .

I then attempted to transfer the airdropped amount from  token addresses #1 to #2 but the balance didn't update  for token address #2 (the amount was debited on #1).

Upon further inspection, it appears a new child token account has been created on the token account with the address #2 - lets call this new token account #3 pXPoTQRP9aQ5KgoFCnmnwDrBK29Jw819SyTihConcxU.

Token account #3 has the tokens I means to transfer to #2. I am now unable to access them. 

I used the latest RC for KineticSdk.MakeTransfer. Is this a bug? 

All on the devnet.

**Comment by wirelessjeano** [comment]
Following on from my comment above, its seems to be that when you transfer between the addresses returned in the "source" field returned from KineticSdk.CreateAccount - it all works fine. Its just a bit confusing. KineticSdk.GetTokenAccounts doesnt seem to serve any purpose in terms of transferring tokens.

**Comment by beeman** [comment]
Hi there, it would be helpful if you could provide code snippets or links to the Solana Explorer to point to accounts. Thanks

**Comment by beeman** [comment]
As a general comment, always send to the account owner, you should not have to worry about the token account as it will be handled for you by the SDK.

**Comment by wirelessjeano** [comment]
All sorted thanks. p.s I ported the latest RC for Unity over to .NET 7 -  https://github.com/wirelessjeano/kinetic-dotnet-sdk. It is working well.

**Comment by beeman** [comment]
> All sorted thanks. p.s I ported the latest RC for Unity over to .NET 7 - https://github.com/wirelessjeano/kinetic-dotnet-sdk. It is working well.

Nice work! What do you intend to use it for?

**Comment by wirelessjeano** [comment]
I have built a web based poker game and I want to see if I can put the entire bet / game / pot / win loop on-chain.  
Players have 15 seconds to complete their turn. Its a classic turn based poker game. 

My initial benchmarks for the endpoints are:

Create account - 15 seconds - this is fine as it will happen asynchronously. 
Get balance - 2 seconds - this is also fine as I can keep track of balances without hitting this.

Make transfer - 20 seconds - this is problematic. Its way too long to do on each players turn synchronously. 

Looking at the payload timestamps below, it looks like the Solana devnet itself is actually pretty quick.   
Where do you think all the time is being lost?  

Is it the KRE tracking on the sandbox Kinetic API endpoint  "/api/transaction/make-transfer"?

How long does the KineticSdk.MakeTransfer() call take on a machine with decent resources?

`"transaction": {
    "id": "clc0m2enu00pusv0s5ceeqmbi",
    "createdAt": "2022-12-23T14:31:37.915Z",
    "updatedAt": "2022-12-23T14:31:38.31Z",
    "amount": "100",
    "decimals": 5,
    "destination": "DosRGPSDvNFdRKTXDNffKynKhscy5uzBPq7yx8oTszAb",
    "errors": [],
    "explorerUrl": null,
    "feePayer": "MogXFseNqiFnRtk6wrDL9BDfKRZhjP5VBSiE1E35zeJ",
    "ip": "102.65.2.58",
    "mint": "KinDesK3dYWo3R2wDk6Ucaf31tvQCCSYyL8Fuqp33GX",
    "processingDuration": 15,
    "referenceId": null,
    "referenceType": null,
    "signature": "5RgB8caGiQCrSZafLe4VxoP8jN6A8b4Qm7GansDJoUp12zLW1zDhLDLXFia8sDKaj8zqao2i588JXGkF5JBgfnSi",
    "solanaCommitted": "2022-12-23T14:31:38.309Z",
    "solanaCommittedDuration": 363,
    "solanaFinalized": null,
    "solanaFinalizedDuration": null,
    "solanaStart": "2022-12-23T14:31:37.946Z",
    "solanaTransaction": null,
    "source": "E9WwMT77m7R1TBUH7wkzjCZm3CPsSoAqFvwGQ5Pmyi5t",
    "status": "Committed",
    "totalDuration": null,
    "tx": "AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfbt80Rxh006svy/qL2EpVuglmPoTv/Mf4FRQBocRhpNI3wlhujb38kNO/becabc9DmkUreHavh0XZflmAXb4OAgEDBwVUZiYHZMj7IkiPhv7K+obQHaqhDITwYhDxBEXBdZTXw1ZtMD75NIA6429U+CIaKEEAp3U5LwEhd3lQYUC1CJ++Tffzv8bMqJjvPLtkNN3325va5HFpD9/YCmdZlecyoNDM+MJfn8wCtIfDmFqAGTNbXMgaTMkMjgk8VRpZUSIxBMux5zLEsJVpFOr5Alf3YrkqslP4Is2f1uA3hQld2wwFSlNQ+F3IgtYUpVZyeIopbd8eq6vQpgZ4iEky9O72oAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpDV8xNISJS87d1VaIo+BG6hmCD7gFOkUfFad/5XByafICBQEBLEJRUUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE9BgQDBAIBCgyAlpgAAAAAAAU=",
    "ua": "Kinetic Dotnet SDK@1.0.0-rc.12",
    "webhookEventStart": null,
    "webhookEventEnd": null,
    "webhookEventDuration": null,
    "webhookVerifyStart": null,
    "webhookVerifyEnd": null,
    "webhookVerifyDuration": null
  }`
